"""Authoritative CBC known-answer gate for Experiment 1; never times ciphers."""
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from unittest.mock import patch

from common import cipher, modules

FIPS81 = "https://nvlpubs.nist.gov/nistpubs/Legacy/FIPS/fipspub81.pdf"
TDES = "https://csrc.nist.gov/csrc/media/projects/cryptographic-standards-and-guidelines/documents/examples/tdes_cbc.pdf"
SP38A = "https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf"
PLAINTEXT = ("6bc1bee22e409f96e93d7e117393172a"
             "ae2d8a571e03ac9c9eb76fac45af8e51"
             "30c81c46a35ce411e5fbc1191a0a52ef"
             "f69f2445df4f9b17ad2b417be66c3710")

# Published expected outputs, not generated by the implementation under test.
VECTORS = [
    ("DES", FIPS81, "Table C1", "0123456789abcdef", "1234567890abcdef",
     "4e6f77206973207468652074696d6520666f7220616c6c20",
     "e5c7cdde872bf27c43e934008c389c0f683788499a7c05f6"),
    ("3DES", TDES, "Three-key CBC example, pages 1-3",
     "0123456789abcdef23456789abcdef01456789abcdef0123", "f69f2445df4f9b17",
     PLAINTEXT[:64], "2079c3d53aa763e193b79e2569ab5262516570481f25b50f73c0bda85c8e0da7"),
    ("AES-128", SP38A, "F.2.1 / F.2.2", "2b7e151628aed2a6abf7158809cf4f3c",
     "000102030405060708090a0b0c0d0e0f", PLAINTEXT,
     "7649abac8119b246cee98e9b12e9197d5086cb9b507219ee95db113a917678b2"
     "73bed6b8e3c1743b7116e69e222295163ff1caa1681fac09120eca307586e1a7"),
    ("AES-192", SP38A, "F.2.3 / F.2.4",
     "8e73b0f7da0e6452c810f32b809079e562f8ead2522c6b7b",
     "000102030405060708090a0b0c0d0e0f", PLAINTEXT,
     "4f021db243bc633d7178183a9fa071e8b4d9ada9ad7dedf4e5e738763f69145a"
     "571b242012fb7ae07fa9baac3df102e008b0e27988598881d920a9e64f5615cd"),
    ("AES-256", SP38A, "F.2.5 / F.2.6",
     "603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4",
     "000102030405060708090a0b0c0d0e0f", PLAINTEXT,
     "f58c4c04d6e5f1ba779eabfb5f7bfbd69cfc4e967edb808d679f777bc6702c7d"
     "39f23369a9d9bacfa530e26304231461b2eb05e2c39be9fcda6c19078c6a9d1b"),
]


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def verify_software_dispatch():
    """Observe native initialization, restoring private hooks before any timing."""
    aes, _, _ = modules()
    counts = {}
    original = aes._raw_aes_lib

    class Observer:
        def __getattr__(self, name):
            return getattr(original, name)

        def AES_start_operation(self, *args):
            counts[current] += 1
            return original.AES_start_operation(*args)

    class Forbidden:
        def __getattr__(self, name):
            raise RuntimeError("Software request accessed AES-NI native library")

    with patch.object(aes, "_raw_aes_lib", Observer()), patch.object(aes, "_raw_aesni_lib", Forbidden()):
        for current, length in (("AES-128", 16), ("AES-192", 24), ("AES-256", 32)):
            counts[current] = 0
            for operation in ("encrypt", "decrypt"):
                obj = cipher(current, bytes(length), "CBC", bytes(16), "software")
                getattr(obj, operation)(bytes(16))
            if counts[current] != 2:
                raise RuntimeError(f"Unverified software dispatch: {current}")
    return {"passed": True, "native_start_calls": counts,
            "path": "Crypto.Cipher._raw_aes (use_aesni=False)",
            "aes_module_sha256": hashlib.sha256(Path(aes.__file__).read_bytes()).hexdigest(),
            "limit": "Library dispatch observation, not an instruction trace"}


def validate_cpu(path, backend="software", session_id=None, purpose="smoke"):
    report = {"passed": False, "started_utc": utc_now(), "mode": "CBC",
              "aes_backend": backend, "session_id": session_id, "purpose": purpose,
              "vectors": []}
    try:
        for name, source, section, key, iv, plaintext, expected in VECTORS:
            row = dict(algorithm=name, source=source, section=section, key=key, iv=iv,
                       plaintext=plaintext, expected_ciphertext=expected, passed=False)
            report["vectors"].append(row)
            k, v, p, c = map(bytes.fromhex, (key, iv, plaintext, expected))
            row["encrypt_passed"] = cipher(name, k, "CBC", v, backend).encrypt(p) == c
            # Decrypt the published ciphertext, never an output generated above.
            row["decrypt_passed"] = cipher(name, k, "CBC", v, backend).decrypt(c) == p
            row["passed"] = row["encrypt_passed"] and row["decrypt_passed"]
            if not row["passed"]:
                raise RuntimeError(f"CBC known-answer validation failed: {name}")
        if backend == "software":
            report["dispatch"] = verify_software_dispatch()
        report["passed"] = True
    except Exception as exc:
        report["error"] = f"{type(exc).__name__}: {exc}"
        raise
    finally:
        report["completed_utc"] = utc_now()
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("x", encoding="utf-8") as output:
            output.write(json.dumps(report, indent=2) + "\n")
    return report
